config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :users, :only => [:index]
  resources :foods, :only => [:index, :new, :create, :edit, :update, :destroy]
  resources :recipes, :only => [:new, :create, :edit, :update, :destroy]
  resources :menus
  resources :orders, :only => [:index, :new, :create, :edit, :update, :destroy]
  get '/',  to: 'top#index'
  get 'order_search', to: 'orders#search'
  get 'user_search', to: 'users#search'
  post 'guest_sign_in', to: 'top#guest_sign_in'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  has_many :recipes, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :name, :price, :user_id, presence: true
  validates :price, numericality: { only_integer: true }

  # メニューの原価を計算する機能
  def menu_cost
    cost = 0
    recipes.each do |recipe|
      cost += recipe.food.unit_price_per_kilo * recipe.gram / 1000
    end
    cost
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!
  def index
    @menus = Menu.where(user_id: current_user)
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      flash[:notice] = 'メニュー登録が完了しました'
      redirect_to menus_path
    else
      flash.now[:alert] = '登録できませんでした'
      render new_menu_path, status: :unprocessable_entity
    end
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    @menu = Menu.find(params[:id])
    if @menu.update(menu_params)
      flash[:notice] = 'メニューを更新しました'
      redirect_to menus_path
    else
      flash.now[:alert] = '更新できませんでした'
      render 'menus/edit', status: :unprocessable_entity
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    flash[:notice] = 'メニューを削除しました'
    redirect_to menus_path
  end

  private

  def menu_params
    params.require(:menu).permit(:name, :price, :user_id)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/edit.html.erb
<div class="box">
  <div class="box-inner">
    <h1>メニュー編集</h1>
    <%= form_for(@menu, url: menu_path) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <dl>
        <dt><%= f.label :name, 'メニュー名' %></dt>
        <dd><%= f.text_field :name %></dd>
      </dl>
      <dl>
        <dt><%= f.label :price, '価格' %></dt>
        <dd><%= f.number_field :price %></dd>
      </dl>
      <div class="form_btn">
        <%= f.submit class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>>

app/views/menus/index.html.erb
<h1>メニュー一覧</h1>
<table class="index_table">
  <tr>
    <th>メニュー名</th>
    <th>価格（円）</th>
    <th>原価（円）</th>
    <th colspan="3"></th>
  </tr>
  <% @menus.each do |menu| %>
    <tr>
      <td><%= menu.name %></td>
      <td><%= menu.price %></td>
      <td><%= menu.menu_cost %></td>
      <td><%= button_to '詳細', menu_path(menu), method: :get %></td>
      <td><%= button_to '編集', edit_menu_path(menu), method: :get %></td>
      <td><%= button_to '削除', menu_path(menu), method: :delete, form: { data: { turbo_confirm: "本当に削除しますか？" } } %></td>
    </tr>
  <% end %>
</table>

app/views/menus/new.html.erb
<div class="box">
  <div class="box-inner">
    <h1>メニュー登録</h1>
    <%= form_for(@menu, url: menus_path, method: :post) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <dl>
        <dt><%= f.label :name, 'メニュー名' %></dt>
        <dd><%= f.text_field :name %></dd>
      </dl>
      <dl>
        <dt><%= f.label :price, '価格' %></dt>
        <dd><%= f.number_field :price %></dd>
      </dl>
      <div class="form_btn">
        <%= f.submit class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/menus/show.html.erb
<h1>メニュー詳細</h1>
<div class="menu_detail">
  <dl>
    <dt>メニュー名</dt>
    <dd><%= @menu.name %></dd>
  </dl>
  <dl>
    <dt>価格</dt>
    <dd><%= @menu.price %>円</dd>
  </dl>
  <dl>
    <dt>原価</dt>
    <dd><%= @menu.menu_cost %>円</dd>
  </dl>
  <dl>
    <dt>原価率</dt>
    <dd><%= @menu.menu_cost / @menu.price.to_f * 100 %>%</dd>
  </dl>
</div>
<table class="index_table">
  <tr>
    <th>使用食材</th>
    <th>使用グラム数</th>
    <th colspan="2"></th>
  </tr>
  <% @menu.recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.food.name %></td>
      <td><%= recipe.gram %>g</td>
      <td><%= button_to '編集', edit_recipe_path(recipe), method: :get %></td>
      <td><%= button_to '削除', recipe_path(recipe), method: :delete, form: { data: { turbo_confirm: "本当に削除しますか？" } } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'レシピ登録', new_recipe_path(menu_id: @menu), class: 'btn' %>