config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :users, :only => [:index]
  resources :foods, :only => [:index, :new, :create, :edit, :update, :destroy]
  resources :recipes, :only => [:new, :create, :edit, :update, :destroy]
  resources :menus
  resources :orders, :only => [:index, :new, :create, :edit, :update, :destroy]
  get '/',  to: 'top#index'
  get 'order_search', to: 'orders#search'
  get 'user_search', to: 'users#search'
  post 'guest_sign_in', to: 'top#guest_sign_in'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  belongs_to :food
  validates :gram, :user_id, presence: true
  validates :gram, numericality: { only_integer: true }
  validates :food_id, uniqueness: { scope: :menu_id }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  def new
    @recipe = Recipe.new
    @foods = Food.where(user_id: current_user.id)
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @foods = Food.where(user_id: current_user.id)
    if @recipe.save
      flash[:notice] = 'レシピ登録が完了しました'
      redirect_to menu_path(@recipe.menu)
    else
      flash[:alert] = '登録できませんでした'
      flash[:errors] = @recipe.errors.full_messages
      redirect_to new_recipe_path(menu_id: @recipe.menu_id)
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @foods = Food.where(user_id: current_user.id)
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_update)
      flash[:notice] = 'レシピを更新しました'
      redirect_to menu_path(@recipe.menu)
    else
      flash.now[:alert] = '更新できませんでした'
      render 'recipes/edit', status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'レシピを削除しました'
    redirect_to menu_path(@recipe.menu)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:gram, :user_id, :menu_id, :food_id)
  end

  def recipe_update
    params.require(:recipe).permit(:gram, :food_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/edit.html.erb
<div class="box">
  <div class="box-inner">
    <h1>レシピ編集</h1>
    <%= form_for(@recipe, url: recipe_path) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <dl>
        <dt>食材名</dt>
        <dd><%= @recipe.food.name %></dd>
      </dl>
      <dl>
        <dt><%= f.label :gram, 'グラム数' %></dt>
        <dd><%= f.number_field :gram %></dd>
      </dl>
      <div class="form_btn">
        <%= f.submit class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="box">
  <div class="box-inner">
    <h1>レシピ登録</h1>
    <%= form_for(@recipe, url: recipes_path, method: :post) do |f| %>
      <% if flash[:errors].present? %>
        <div class="alert alert-warning">
          <ul>
            <% flash[:errors].each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :menu_id, value: params[:menu_id] %>
      <dl>
        <dt><%= f.label :food_id, '食材' %></dt>
        <dd><%= f.collection_select :food_id, @foods.all, :id, :name, { include_blank: '食材を選択してください' } %></dd>
      </dl>
      <dl>
        <dt><%= f.label :gram, 'グラム数' %></dt>
        <dd><%= f.number_field :gram %></dd>
      </dl>
      <div class="form_btn">
        <%= f.submit class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>