config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :users, :only => [:index]
  resources :foods, :only => [:index, :new, :create, :edit, :update, :destroy]
  resources :recipes, :only => [:new, :create, :edit, :update, :destroy]
  resources :menus
  resources :orders, :only => [:index, :new, :create, :edit, :update, :destroy]
  get '/',  to: 'top#index'
  get 'order_search', to: 'orders#search'
  get 'user_search', to: 'users#search'
  post 'guest_sign_in', to: 'top#guest_sign_in'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  validates :output, :year_and_month, :user_id, presence: true
  validates :output, numericality: { only_integer: true }
  validates :year_and_month, uniqueness: { scope: :menu_id }

  # 日付検索機能
  def self.day_search(day)
    where(year_and_month: day.values.join('-'))
  end

  # メニューの出数の合計値を返す機能
  def self.output_sum(menu)
    where(menu_id: menu).sum(:output)
  end

  # メニューの構成比を返す機能
  def self.occupancy(menu)
    menu_sum = 0
    all_sum = 0
    where(menu_id: menu).each do |order|
      menu_sum += order.menu.price * order.output
    end
    all.each do |order|
      all_sum += order.menu.price * order.output
    end
    (menu_sum / all_sum.to_f * 100).round(2)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders = Order.where(user_id: current_user)
    @menus = Menu.where(user_id: current_user)
    @view = 'index'
  end

  def new
    @order = Order.new
    @menus = Menu.where(user_id: current_user)
  end

  def create
    @orders = orders_params
    is_break = false
    @orders.each do |orders|
      @order = Order.new(order_params)
      @order.user_id = orders[:user_id]
      @order.menu_id = orders[:menu_id]
      @order.output = orders[:output]
      unless @order.save
        is_break = true
        break
      end
    end
    if is_break
      flash[:alert] = '登録できませんでした'
      flash[:error] = @order.errors.full_messages
      redirect_to new_order_path
    else
      flash[:notice] = '出数登録が完了しました'
      redirect_to orders_path
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_update_params)
      flash[:notice] = '出数を更新しました'
      redirect_to orders_path
    else
      flash.now[:alert] = '更新できませんでした'
      render 'orders/edit', status: :unprocessable_entity
    end
  end

  def search
    @menus = Menu.where(user_id: current_user)
    @orders = Order.where(user_id: current_user).day_search(params[:date])
    @view = 'search'
    render 'orders/index'
  end

  private

  def order_params
    params.require(:order).permit(:year_and_month)
  end

  def orders_params
    params.require(:orders).map do |orders|
      orders.permit(:user_id, :output, :menu_id)
    end
  end

  def order_update_params
    params.require(:order).permit(:output)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<div class="box">
  <div class="box-inner">
    <h1>出数編集</h1>
    <%= form_for(@order, url: order_path) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <dl>
        <dt><%= @order.year_and_month.strftime('%Y年%m月') %></dt>
        <dd><%= @order.menu.name %></dd>
      </dl>
      <dl>
        <dt><%= f.label :output, '出数' %></dt>
        <dd><%= f.number_field :output %></dd>
      </dl>
      <div class="form_btn">
        <%= f.submit class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/index.html.erb
<h1>出数管理</h1>
<h4>データ検索</h4>
<div class="search_form">
  <div>
    <%= form_tag(order_search_path, :method => "get") do %>
      <%= date_select(:date, :year_and_month, discard_day: true) %>
      <%= submit_tag "表示する" %>
    <% end %>
  </div>
  <div>
    <%= link_to '累計出数表示', orders_path, class: 'total_search' %>
  </div>
</div>
<% if @view == 'index' %>
  <h3>トータル出数</h3>
<% else %>
  <h3><%= "#{params[:date]['year_and_month(1i)']}年#{params[:date]['year_and_month(2i)']}月" %></h3>
<% end %>
<table class="index_table">
  <tr>
    <th>メニュー名</th>
    <% if @orders.present? %>
      <th>出数</th>
    <% end %>
    <% if @view == 'search' %>
      <th></th>
    <% end %>
  </tr>
  <% @menus.each do |menu| %>
    <tr>
      <% if menu.name.present? %>
        <td>
          <%= menu.name %>
        </td>
      <% end %>
      <% if @orders.present? %>
        <td>
          <%= @orders.where(menu_id: menu.id).sum { |hash| hash[:output] } %>
        </td>
        <% if @view == 'search' %>
          <% if @orders.where(menu_id: menu.id).present? %>
            <td>
              <%= link_to '編集', edit_order_path(@orders.where(menu_id: menu.id).first.id) %>
            </td>
          <% end %>
        <% end %>
      <% end %>
    </tr>
  <% end %>
</table>
<%= link_to '月間出数新規登録', new_order_path, class: 'btn' %>

app/views/orders/new.html.erb
<div class="box">
  <div class="box-inner">
    <h1>出数登録</h1>
    <% if flash[:error].present? %>
      <div class="alert alert-warning">
        <ul>
          <% flash[:error].each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_for(@order, url: orders_path) do |f| %>
      <dl>
        <dt><%= f.label :year_and_month, '年月' %></dt>
        <dd><%= f.date_select :year_and_month, discard_day: true  %></dd>
      </dl>
      <% @menus.each do |menu| %>
        <%= f.hidden_field :user_id, value: current_user.id, name: "orders[][user_id]" %>
        <%= f.hidden_field :menu_id, value: menu.id, name: "orders[][menu_id]" %>
        <dl>
          <dt><%= f.label :output, menu.name %></dt>
          <dd><%= f.number_field :output, name: "orders[][output]" %></dd>
        </dl>
      <% end %>
      <div class="form_btn">
        <%= f.submit class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>