config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :users, :only => [:index]
  resources :foods, :only => [:index, :new, :create, :edit, :update, :destroy]
  resources :recipes, :only => [:new, :create, :edit, :update, :destroy]
  resources :menus
  resources :orders, :only => [:index, :new, :create, :edit, :update, :destroy]
  get '/',  to: 'top#index'
  get 'order_search', to: 'orders#search'
  get 'user_search', to: 'users#search'
  post 'guest_sign_in', to: 'top#guest_sign_in'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CostManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- リセットcss -->
    <link href="https://unpkg.com/sanitize.css" rel="stylesheet"/>
    <!-- アイコン -->
    <link href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <%= link_to "/" do%>
        <div class="logo">
          <h1>CostManagement</h1>
        </div>
      <% end %>
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <button class="navbar-toggler responsive" type="button" onclick="showbox();" >
              <i class="fas fa-bars"></i>
            </button>
          <% else %>
            <li><a href="/#about">概要</a></li>
            <li><%= link_to '新規登録', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <div class="flash">
      <% if notice %>
        <p class="notice flash_message"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert flash_message"><%= alert %></p>
      <% end %>
    </div>
    <% if current_user %>
      <div class="wrapper">
        <div class="side" id="side">
          <ul>
            <button class="navbar_hide responsive" type="button" onclick="hidebox();" >
              <li>メニューを閉じる</li>
            </button>
            <li><%= link_to 'マイページ', users_path %></li>
            <li><%= link_to '食材登録', new_food_path %></li>
            <li><%= link_to '食材一覧', foods_path %></li>
            <li><%= link_to 'メニュー登録', new_menu_path %></li>
            <li><%= link_to 'メニュー一覧', menus_path %></li>
            <li><%= link_to '月間出数管理', orders_path %></li>
            <li class="responsive" ><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
            <li class="responsive" ><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <div class="content">
          <div class="content_main">
            <%= yield %>
          </div>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
    <footer><p>CostManagement</p></footer>
  </body>
  <script>
    function showbox(){
      document.getElementById("side").style.display = "block";
    }
    function hidebox(){
      document.getElementById("side").style.display = "none";
    }
  </script>
</html>